"""
End-to-End Minimum-Cost Multicommodity Flow (MCMCF) Script.

This script demonstrates how instances generated by 's2mflow' (either loaded from disk 
or generated dynamically in-memory) can be immediately converted into a Pyomo model and 
solved using the open-source HiGHS solver.
"""

import os
import time
import s2mflow
import pyomo.environ as pyo


def solve_mcmcf_framework(
    nodes,
    base_edges,
    commodity_edges,
    num_commodities,
    capacities,
    commodity_capacities,
    commodity_weights,
    supply_demand_data,
    solver_name: str = "highs"
):
    """
    Mathematical enginge that builds and solves the MCMCF algebraic model.
    """
    print(f"[*] Constructing optimization model.")
    print(f"[*] Instance Profile: {len(nodes)} nodes, {len(base_edges)} arcs, {num_commodities} commodities.")

    # 1. Initialize Pyomo Model
    model = pyo.ConcreteModel()

    # 2. Variables with edge-wise capacity bounds: 0 <= x_e^k <= u_e^k
    def commodity_edge_bounds(m, k, u, v):
        upper_bound = commodity_capacities[(u, v)][k]
        return (0.0, float(upper_bound))
    
    model.flow = pyo.Var(
        commodity_edges,
        domain=pyo.NonNegativeReals,
        bounds=commodity_edge_bounds,
        name="x",
    )

    # 3. Objective Function: Minimze Sum of (c_e^k * x_e^k)
    model.obj = pyo.Objective(
        expr=sum(
            model.flow[k, u, v] * commodity_weights[(u, v)][k]
            for (k, u, v) in commodity_edges
        ),
        sense=pyo.minimize
    )

    # 4. Shared Mutual Capacity Constraints: sum_k x_e^k <= u_e
    model.shared_caps = pyo.ConstraintList()
    for i, (u, v) in enumerate(base_edges):
        shared_cap = capacities[i]
        model.shared_caps.add(
            sum(model.flow[k, u, v] for k in range(num_commodities)) <= shared_cap
        )

    # 5. Flow Conservation Constraints
    model.flow_balance = pyo.ConstraintList()
    incoming, outgoing = s2mflow.get_adjacency_mapping(nodes, base_edges)

    for k in range(num_commodities):
        for node in nodes:
            in_flow = sum(model.flow[k, u, node] for u in incoming.get(node, []))
            out_flow = sum(model.flow[k, node, v] for v in outgoing.get(node, []))

            demand = supply_demand_data[node][k] if node in supply_demand_data else 0.0

            model.flow_balance.add(out_flow - in_flow == demand)
    
    # 6. Execute Solver Call
    print(f"[*] Solver Call")
    start_time = time.perf_counter()
    results = pyo.SolverFactory(solver_name).solve(model, tee=True)
    end_time = time.perf_counter()

    try:
        solver_runtime = results.solver.time
    except AttributeError:
        solver_runtime = end_time - start_time
    
    print(f"[+] Objective Value: {pyo.value(model.obj)}")
    print(f"[+] Solver Runtime: {solver_runtime} seconds")


def run_parsed_file_workflow(
    file_path: str,
    solver_name: str = "highs"
):
    """
    Workflow 1: Solves a fully self-contained multicommodity instance parsed from disk.
    """
    if not os.path.exists(file_path):
        print(f"[-] Parsed target file skip: {file_path} (does not exits).")
        return

    # Parse MCMCF instance using s2mflow
    print(f"[*] Loading multicommodity instance: {file_path}")
    mc_instance = s2mflow.load_multi_commodity_instance(file_path)

    # Extract attributes to forward to optimization model
    solve_mcmcf_framework(
        nodes=mc_instance.nodes,
        base_edges=mc_instance.edges,
        commodity_edges=mc_instance.commodity_edges,
        num_commodities=mc_instance.num_commodities,
        capacities=mc_instance.capacities,
        commodity_capacities=mc_instance.commodity_capacities,
        commodity_weights=mc_instance.commodity_weights,
        supply_demand_data=mc_instance.commodity_supply_demand_data,
        solver_name=solver_name,
    )


def run_generation_and_solve_workflow(
    base_net_path: str,
    num_commodities: int = 3,
    solver_name: str = "highs",
):
    """
    Workflow 2: Loads a baseline single-commodity graph, generates multicommodity data and solves MCMCF.  
    """
    if not os.path.exists(base_net_path):
        raise FileNotFoundError(f"Base network instance not found: {base_net_path}")

    print(f"[*] Loading baseline single-commodity network: {base_net_path}")
    net_instance = s2mflow.load_min_instance(base_net_path)

    # Create multicommodity data
    print(f"[*] Generate multicommodity data via s2mflow ...")
    mc_data = s2mflow.generate_multi_commodity_data(
        instance=net_instance,
        num_commodities=num_commodities,
        is_uniform=False,
        randomize_caps=False,
        randomize_costs=False,
        seed=512,
    )

    solve_mcmcf_framework(
        nodes=net_instance.nodes,
        base_edges=net_instance.arcs,
        commodity_edges=mc_data.commodity_edges,
        num_commodities=mc_data.num_commodities,
        capacities=net_instance.capacities,
        commodity_capacities=mc_data.commodity_capacities,
        commodity_weights=mc_data.commodity_weights,
        supply_demand_data=mc_data.supply_partition,
        solver_name=solver_name
    )


if __name__ == "__main__":
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    NUM_COMMODITIES = [2, 5, 10]
    SOLVER_NAMES = ["highs"]

    for solver_name in SOLVER_NAMES:
        for i in range(1, 5):
            NETWORK_MIN_FILE = os.path.join(BASE_DIR, "data", f"net_instance_{i}", f"netgen_{i}.min")
            for k in NUM_COMMODITIES:
                print(f"=== Starting MCMCF Optimization Pipeline (Solver = {solver_name}) ===")
                print(f"Network instance: netgen_{i}.min | Number of commodities: {k}")

                run_generation_and_solve_workflow(NETWORK_MIN_FILE, num_commodities=k, solver_name=solver_name)

                PARSED_MC_FILE = os.path.join(BASE_DIR, "data", f"net_instance_{i}", f"netgen_{i}_{k}.mcfmin")

                run_parsed_file_workflow(PARSED_MC_FILE, solver_name=solver_name)

