"""
End-to-End Minimum-Cost Multicommodity Flow (MCMCF) Script via gurobipy.

This script demonstrates how instances generated by 's2mflow' can be converted
directly into a native Gurobi model and solved.
"""

import os
import time
import s2mflow
import gurobipy as grb


def solve_mcmcf_framework_gurobi(
    nodes,
    base_edges,
    commodity_edges,
    num_commodities,
    capacities,
    commodity_capacities,
    commodity_weights,
    supply_demand_data,
    method: int = 1,
):
    """
    Mathematical engine that builds and solves the MCMCF model directly via Gurobipy.
    """
    print(f"[*] Constructing Gurobi optimization model.")
    print(f"[*] Instance Profile: {len(nodes)} nodes, {len(base_edges)} arcs, {num_commodities} commodities.")

    # 1. Initialize Gurobi Environment and Model
    model = grb.Model("MCMCF_Direct")
    model.setParam("Method", method)

    # 2. Decision Variables with explicit edge-wise capacity bounds: 0 <= x_e^k <= u_e^k
    # We populate the bounds dynamically during creation to match our framework layout
    upper_bounds = []
    for (k, u, v) in commodity_edges:
        upper_bounds.append(commodity_capacities[(u, v)][k])
    
    flow = model.addVars(
        commodity_edges,
        lb=0.0,
        ub=upper_bounds,
        vtype=grb.GRB.CONTINUOUS,
        name="x"
    )

    # 3. Objective Function: Minimize Sum of (c_e^k * x_e^k)
    model.setObjective(
        grb.quicksum(flow[k, u, v] * commodity_weights[(u, v)][k] for (k, u, v) in commodity_edges),
        sense=grb.GRB.MINIMIZE
    )

    # 4. Shared Mutual Capacity Constraints: sum_k x_e^k <= u_e
    model.addConstrs(
        (
            grb.quicksum(flow[k, u, v] for k in range(num_commodities)) <= capacities[i]
            for i, (u, v) in enumerate(base_edges)
        ),
        name="Shared_Cap"
    )

    # 5. Flow Conservation Constraints
    incoming, outgoing = s2mflow.get_adjacency_mapping(nodes, base_edges)

    for k in range(num_commodities):
        for node in nodes:
            in_flow = grb.quicksum(flow[k, u, node] for u in incoming.get(node, []))
            out_flow = grb.quicksum(flow[k, node, v] for v in outgoing.get(node, []))

            demand = supply_demand_data[node][k] if node in supply_demand_data else 0.0

            model.addConstr(out_flow - in_flow == demand, name=f"balance_{k}_{node}")

    # 6. Execute Solver Call
    print(f"[*] Gurobi: Solve model (Method = {method})")
    start_time = time.perf_counter()
    model.optimize()
    end_time = time.perf_counter()

    solver_runtime = model.Runtime if model.Status == grb.GRB.OPTIMAL else end_time - start_time
    
    if model.Status == grb.GRB.OPTIMAL:
        print(f"[+] Objective Value: {model.ObjVal}")
        print(f"[+] Solver Runtime: {solver_runtime:.6f} seconds\n")
    else:
        print(f"[-] Solver encountered termination code: {model.Status}\n")


def run_parsed_file_workflow(
    file_path: str,
    method: int = 1,
):
    """Workflow 1: File-Parsing via Gurobi"""
    if not os.path.exists(file_path):
        print(f"[-] Target file skip: {file_path} (does not exist).")
        return

    print(f"[*] Loading multicommodity instance: {file_path}")
    mc_instance = s2mflow.load_multi_commodity_instance(file_path)

    solve_mcmcf_framework_gurobi(
        nodes=mc_instance.nodes,
        base_edges=mc_instance.edges,
        commodity_edges=mc_instance.commodity_edges,
        num_commodities=mc_instance.num_commodities,
        capacities=mc_instance.capacities,
        commodity_capacities=mc_instance.commodity_capacities,
        commodity_weights=mc_instance.commodity_weights,
        supply_demand_data=mc_instance.commodity_supply_demand_data,
        method=method,
    )


def run_generation_and_solve_workflow(
    base_net_path: str, 
    num_commodities: int = 3, 
    method: int = 1,
):
    """Workflow 2: Live In-Memory Generation via Gurobi"""
    if not os.path.exists(base_net_path):
        raise FileNotFoundError(f"Base network instance not found: {base_net_path}")

    print(f"[*] Loading baseline single-commodity network: {base_net_path}")
    net_instance = s2mflow.load_min_instance(base_net_path)

    print(f"[*] Generate multicommodity data via s2mflow ...")
    mc_data = s2mflow.generate_multi_commodity_data(
        instance=net_instance,
        num_commodities=num_commodities,
        is_uniform=False,
        randomize_caps=False,
        randomize_costs=False,
        seed=512,
    )

    solve_mcmcf_framework_gurobi(
        nodes=net_instance.nodes,
        base_edges=net_instance.arcs,
        commodity_edges=mc_data.commodity_edges,
        num_commodities=mc_data.num_commodities,
        capacities=net_instance.capacities,
        commodity_capacities=mc_data.commodity_capacities,
        commodity_weights=mc_data.commodity_weights,
        supply_demand_data=mc_data.supply_partition,
        method=method,
    )


if __name__ == "__main__":
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    NUM_COMMODITIES = [2, 5, 10]
    METHODS = [1]  # 1 = dual simplex

    for method in METHODS:
        for i in range(1, 5):
            NETWORK_MIN_FILE = os.path.join(BASE_DIR, "data", f"net_instance_{i}", f"netgen_{i}.min")
            
            if not os.path.exists(NETWORK_MIN_FILE):
                continue

            for k in NUM_COMMODITIES:
                print(f"=== Starting Gurobi MCMCF Optimization Pipeline (Method = {method}) ===")
                print(f"Network instance: netgen_{i}.min | Commodities: {k}")

                PARSED_MC_FILE = os.path.join(BASE_DIR, "data", f"net_instance_{i}", f"netgen_{i}_{k}.mcfmin")

                # Run dynamic generation (and save out to generate the file if it doesn't exist)
                run_generation_and_solve_workflow(
                    base_net_path=NETWORK_MIN_FILE, 
                    num_commodities=k, 
                    method=method
                )

                # Re-parse the exact file to ensure file reader mapping compliance
                run_parsed_file_workflow(
                    PARSED_MC_FILE,
                    method=method,
                )